[package]
name = "super_stats_v3_api"
version = "0.1.0"
edition = "2021"


[dependencies]
ic-cdk = { workspace = true }
candid = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
ic-stable-memory = "0.4.4"
hex = "0.4.2"
