[package]
name = "super_stats_v3_api"
version = "0.1.0"
edition = "2021"


[dependencies]
ic-cdk = "0.12.0"
candid = { workspace = true }
serde = "1.0.193"
ic-stable-memory = "0.4.4"
serde_bytes = "0.11.2"
hex = "0.4.2"
#pocket-ic = "2.0.1"
#icrc-ledger-types = { path = "../icrc_types" }


