import {
  GOLDAO_LEDGER_CANISTER_ID,
  GLDT_LEDGER_CANISTER_ID,
  ICP_LEDGER_CANISTER_ID,
  OGY_LEDGER_CANISTER_ID,
  WTN_LEDGER_CANISTER_ID,
  GLDT_STAKE_CANISTER_ID,
  GOLDAO_LEDGER_CANISTER_ID_IC,
  GLDT_LEDGER_CANISTER_ID_IC,
  ICP_LEDGER_CANISTER_ID_IC,
  OGY_LEDGER_CANISTER_ID_IC,
  WTN_LEDGER_CANISTER_ID_IC,
  GLDT_STAKE_CANISTER_ID_IC,
} from "../constants";

export const getCanister = (env) => {
  const canisters = {
    staging: {
      GOLDAO_LEDGER_CANISTER_ID: GOLDAO_LEDGER_CANISTER_ID,
      GLDT_LEDGER_CANISTER_ID: GLDT_LEDGER_CANISTER_ID,
      ICP_LEDGER_CANISTER_ID: ICP_LEDGER_CANISTER_ID,
      OGY_LEDGER_CANISTER_ID: OGY_LEDGER_CANISTER_ID,
      WTN_LEDGER_CANISTER_ID: WTN_LEDGER_CANISTER_ID,
      GLDT_STAKE_CANISTER_ID: GLDT_STAKE_CANISTER_ID,
    },
    production: {
      GOLDAO_LEDGER_CANISTER_ID: GOLDAO_LEDGER_CANISTER_ID_IC,
      GLDT_LEDGER_CANISTER_ID: GLDT_LEDGER_CANISTER_ID_IC,
      ICP_LEDGER_CANISTER_ID: ICP_LEDGER_CANISTER_ID_IC,
      OGY_LEDGER_CANISTER_ID: OGY_LEDGER_CANISTER_ID_IC,
      WTN_LEDGER_CANISTER_ID: WTN_LEDGER_CANISTER_ID_IC,
      GLDT_STAKE_CANISTER_ID: GLDT_STAKE_CANISTER_ID_IC,
    },
  };
  return canisters[env];
};
