spec:
  inputs:
    src-folder:
      description: Name of the source folder, should be the same as the canister's cargo package name.
      options:
        [
          "gldt_core",
          "icp_neuron",
          "token_metrics",
          "sns_rewards",
          "cycles_manager",
          "integration_testing",
          "management"
        ]
---
# Rust canister unit test with coverage

$[[ inputs.src-folder ]] tests:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "backend/libraries/{**,**/**,**/**/**}/*.{rs,toml,lock}"
        - "backend/external_canisters/{**,**/**,**/**/**}/*.{rs,toml,lock}"
        - "backend/canisters/$[[ inputs.src-folder ]]/{**,**/**,**/**/**}/*.{rs,toml,lock}"
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
      changes:
        - "backend/libraries/{**,**/**,**/**/**}/*.{rs,toml,lock}"
        - "backend/external_canisters/{**,**/**,**/**/**}/*.{rs,toml,lock}"
        - "backend/canisters/$[[ inputs.src-folder ]]/{**,**/**,**/**/**}/*.{rs,toml,lock}"
    - if: $CI_COMMIT_REF_NAME == "develop"
      changes:
        - "backend/libraries/{**,**/**,**/**/**}/*.{rs,toml,lock}"
        - "backend/external_canisters/{**,**/**,**/**/**}/*.{rs,toml,lock}"
        - "backend/canisters/$[[ inputs.src-folder ]]/{**,**/**,**/**/**}/*.{rs,toml,lock}"
  extends: .rust template
  tags:
    - dind
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_SECURITY_OPT: "--security-opt seccomp=unconfined"
  script:
    # - cargo tarpaulin -p $[[ inputs.src-folder ]] -j 2 --lib --no-fail-fast -o Xml
    - cargo test -p $[[ inputs.src-folder ]]
  # coverage: /^\d+.\d+% coverage/
  # artifacts:
  #   reports:
  #     coverage_report:
  #       coverage_format: cobertura
  #       path: cobertura.xml
