spec:
  inputs:
    src-folder:
      description: Name of the source folder, should be the same as the canister's cargo package name.
      options:
        [
          "cycles_manager",
          "gldt_core",
          "icp_neuron",
          "management",
          "sns_rewards",
          "token_metrics"
        ]
---
# Rust canisters builds

$[[ inputs.src-folder ]] canister build:
  stage: build
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      when: never
    - if: $CI_COMMIT_REF_NAME == "develop"
      changes:
        - "backend/canisters/$[[ inputs.src-folder ]]/**/*.{rs,toml,lock}"
    - if: $CI_COMMIT_REF_NAME =~ '/^$[[ inputs.src-folder ]]-v\d+\.\d+\.\d+$/'
  extends: .rust template
  script:
    - scripts/build-canister.sh --wasmonly $[[ inputs.src-folder ]]
    - scripts/generate-did.sh $[[ inputs.src-folder ]]
    - scripts/build-canister.sh --checksum $[[ inputs.src-folder ]]
    - ic-wasm backend/canisters/$[[ inputs.src-folder ]]/target/wasm32-unknown-unknown/release/$[[ inputs.src-folder ]]_canister.wasm info
  artifacts:
    name: "${CI_PROJECT_NAME}-$[[ inputs.src-folder ]]-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-wasm"
    paths:
      - backend/canisters/$[[ inputs.src-folder ]]/target/wasm32-unknown-unknown/release
      - backend/canisters/$[[ inputs.src-folder ]]/api/can.did
    expire_in: 6 months

$[[ inputs.src-folder ]] integration-test build:
  stage: integration_testing
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_REF_NAME == "master"
      changes:
        - "backend/libraries/**/*.{rs,toml,lock}"
        - "backend/external_canisters/**/*.{rs,toml,lock}"
        - "backend/canisters/**/*.{rs,toml,lock}"
  extends: .rust template
  script:
    - scripts/build-canister.sh -it $[[ inputs.src-folder ]]
    - scripts/generate-did.sh $[[ inputs.src-folder ]]
  artifacts:
    name: "$[[ inputs.src-folder ]]-${CI_COMMIT_SHORT_SHA}-wasm-INT_TEST_BUILD"
    paths:
      - backend/canisters/$[[ inputs.src-folder ]]/target/wasm32-unknown-unknown/release
    expire_in: 1 day
