spec:
  inputs:
    src-folder:
      description: Name of the source folder, should be the same as the canister's cargo package name.
      options: ["gldt_core", "icp_neuron", "token_metrics", "sns_rewards", "integration_testing"]
---
# Rust canister unit test with coverage

$[[ inputs.src-folder ]] tests:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_REF_NAME == "develop"
  extends: .rust template
  tags:
    - dind
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_SECURITY_OPT: "--security-opt seccomp=unconfined"
  script:
    - cargo tarpaulin -p $[[ inputs.src-folder ]] -j 2 --lib --no-fail-fast -o Xml --rustflags="-C linker=x86_64-unknown-linux-gnu"
  coverage: /^\d+.\d+% coverage/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
