spec:
  inputs:
    src-folder:
      description: The NextJS project folder name. Must be located in the /client/ folder
      options: ["gldt_landing_page", "gldt_explorer", "gld_dashboard", "gldt_swap_app"]
---
# Frontend builds

.build template:
  stage: build
  extends: .node template
  script:
    - ENV=$ENV npm run build:$[[ inputs.src-folder ]]

.short-artifact-template:
  extends: .build template
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}-$[[ inputs.src-folder ]]_BUILD_${ENV}"
    paths:
      - client/$[[ inputs.src-folder ]]/out
    expire_in: 1 day

.long-artifact-template:
  extends: .build template
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}-$[[ inputs.src-folder ]]_BUILD_${ENV}"
    paths:
      - client/$[[ inputs.src-folder ]]/out
    expire_in: 6 months


$[[ inputs.src-folder ]] testing build:
  extends: .short-artifact-template
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_REF_NAME != "develop"
      changes:
        - "client/$[[ inputs.src-folder ]]/*.{js,json}"
        - "client/$[[ inputs.src-folder ]]/**/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
  variables:
    ENV: "local" # local | staging | preprod | prod
  environment:
    name: $[[ inputs.src-folder ]] frontend
    deployment_tier: development
    action: prepare

$[[ inputs.src-folder ]] staging build:
  extends: .short-artifact-template
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_REF_NAME == "develop"
      changes:
        - "client/$[[ inputs.src-folder ]]/*.{js,json}"
        - "client/$[[ inputs.src-folder ]]/**/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
  variables:
    ENV: "staging" # local | staging | preprod | prod
  environment:
    name: $[[ inputs.src-folder ]] frontend
    deployment_tier: staging
    action: prepare

$[[ inputs.src-folder ]] preprod build:
  extends: .short-artifact-template
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_REF_NAME == "develop"
      changes:
        - "client/$[[ inputs.src-folder ]]/*.{js,json}"
        - "client/$[[ inputs.src-folder ]]/**/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
  variables:
    ENV: "preprod" # local | staging | preprod | prod
  environment:
    name: $[[ inputs.src-folder ]] frontend
    deployment_tier: testing
    action: prepare



$[[ inputs.src-folder ]] production build:
  extends: .long-artifact-template
  rules:
    - if: $CI_COMMIT_TAG =~ '/^$[[ inputs.src-folder ]]-v\d+\.\d+\.\d+$/'
      changes:
        - "client/$[[ inputs.src-folder ]]/*.{js,json}"
        - "client/$[[ inputs.src-folder ]]/**/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
  variables:
    ENV: "prod" # local | staging | preprod | prod
  environment:
    name: $[[ inputs.src-folder ]] frontend
    deployment_tier: production
    action: prepare
