spec:
  inputs:
    src-folder:
      description: The frontend project folder name. Must be located in the /client/ folder
      options: ["gldt_landing_page", "gld_dashboard", "gldt_swap_app"]
---
# Frontend builds

$[[ inputs.src-folder ]] test build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "client/$[[ inputs.src-folder ]]/*.{js,json}"
        - "client/$[[ inputs.src-folder ]]/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
  # needs: ["generate test declarations"]
  extends: .node template
  script:
    - VERSION_STRING="${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
    - ENV=$ENV VERSION=$VERSION_STRING npm run build:staging --workspace $[[ inputs.src-folder ]]
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-$[[ inputs.src-folder ]]-TEST"
    paths:
      - client/$[[ inputs.src-folder ]]/dist
    expire_in: 1 day

$[[ inputs.src-folder ]] staging build:
  stage: build
  rules:
    - if: ($CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_REF_NAME == "develop") || ($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_REF_NAME != "develop")
      changes:
        - "client/$[[ inputs.src-folder ]]/*.{js,json}"
        - "client/$[[ inputs.src-folder ]]/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
  # needs: ["generate declarations"]
  extends: .node template
  variables:
    CANISTER_NAME: "$[[ inputs.src-folder ]]"
    NETWORK: "staging"
  script:
    - VERSION_STRING="${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
    - ENV=$ENV VERSION=$VERSION_STRING npm run build:staging --workspace $[[ inputs.src-folder ]]
    - STAGING_URL=$(CAN=$CANISTER_NAME NET=$NETWORK node -e 'const ids=require("./canister_ids.json"); console.log(`https://${ids[process.env.CAN][process.env.NET]}.icp0.io`);')
    - echo "$(echo '$[[ inputs.src-folder ]]' | tr '[:lower:]' '[:upper:]')_URL=$STAGING_URL" > $[[ inputs.src-folder ]]_deploy.env
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}-$[[ inputs.src-folder ]]_STAGING_BUILD"
    paths:
      - client/$[[ inputs.src-folder ]]/dist
    reports:
      dotenv: $[[ inputs.src-folder ]]_deploy.env
    expire_in: 1 day
  environment:
    name: $[[ inputs.src-folder ]] frontend app
    deployment_tier: staging
    action: prepare

$[[ inputs.src-folder ]] preprod build:
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop" && $CI_PIPELINE_SOURCE != "merge_request_event"
      changes:
        - "client/$[[ inputs.src-folder ]]/*.{js,json}"
        - "client/$[[ inputs.src-folder ]]/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
  # needs: ["generate declarations"]
  extends: .node template
  variables:
    CANISTER_NAME: "$[[ inputs.src-folder ]]"
    NETWORK: "preprod"
  script:
    - VERSION_STRING="${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
    - ENV=$ENV VERSION=$VERSION_STRING run build:preprod --workspace $[[ inputs.src-folder ]]
    - PREPROD_URL=$(CAN=$CANISTER_NAME NET=$NETWORK node -e 'const ids=require("./canister_ids.json"); console.log(`https://${ids[process.env.CAN][process.env.NET]}.icp0.io`);')
    - echo "$(echo '$[[ inputs.src-folder ]]' | tr '[:lower:]' '[:upper:]')_URL=$PREPROD_URL" > $[[ inputs.src-folder ]]_deploy.env
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}-$[[ inputs.src-folder ]]_PREPROD_BUILD"
    paths:
      - client/$[[ inputs.src-folder ]]/dist
    reports:
      dotenv: $[[ inputs.src-folder ]]_deploy.env
    expire_in: 1 day
  environment:
    name: $[[ inputs.src-folder ]] frontend app preprod
    deployment_tier: staging
    action: prepare

$[[ inputs.src-folder ]] production build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ '/^$[[ inputs.src-folder ]]-v\d+\.\d+\.\d+$/'
    - if: $CI_COMMIT_REF_NAME == "master"
      changes:
        - "client/$[[ inputs.src-folder ]]/*.{js,json}"
        - "client/$[[ inputs.src-folder ]]/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
  # needs: ["generate declarations"]
  extends: .node template
  variables:
    CANISTER_NAME: "$[[ inputs.src-folder ]]"
    NETWORK: "ic"
  script:
    - VERSION_STRING="${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
    - ENV=$ENV VERSION=$VERSION_STRING run build:production --workspace $[[ inputs.src-folder ]]
    - PRODUCTION_URL=$(CAN=$CANISTER_NAME NET=$NETWORK node -e 'const ids=require("./canister_ids.json"); console.log(`https://${ids[process.env.CAN][process.env.NET]}.icp0.io`);')
    - echo "$(echo '$[[ inputs.src-folder ]]' | tr '[:lower:]' '[:upper:]')_URL=$PRODUCTION_URL" > $[[ inputs.src-folder ]]_deploy.env
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-$[[ inputs.src-folder ]]"
    paths:
      - client/$[[ inputs.src-folder ]]/dist
    reports:
      dotenv: $[[ inputs.src-folder ]]_deploy.env
    expire_in: 6 months
  environment:
    name: $[[ inputs.src-folder ]] frontend app
    deployment_tier: production
    action: prepare
