spec:
  inputs:
    src-folder:
      description: The NextJS project folder name. Must be located in the /client/ folder
      options: ["gldt_landing_page", "gldt_explorer", "gld_dashboard", "gldt_swap_app"]
    sns-controlled:
      description: Whether or not the canister is SNS controlled
      options: ["true", "false"]
---

# STAGING AND PREPROD DEPLOYMENT

.staging deploy template:
  stage: deploy
  resource_group: frontend staging deployment
  variables:
    PEM_FILE: "${PEM_FILE_STAGING}"
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop" && $CI_PIPELINE_SOURCE != "merge_request_event"
      changes:
        - "client/$[[ inputs.src-folder ]]/*.{js,json}"
        - "client/$[[ inputs.src-folder ]]/**/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
  before_script:
    - !reference [.import dfx identity, before_script]

$[[ inputs.src-folder ]] staging deploy:
  extends: .staging deploy template
  variables:
    TARGET_NETWORK: staging
    IS_SNS_CONTROLLED: $[[ inputs.sns-controlled ]]
  needs: ["$[[ inputs.src-folder ]] staging build"]
  script:
     - ENV=staging dfx deploy --network $TARGET_NETWORK --no-wallet --mode reinstall -y $[[ inputs.src-folder ]]
  environment:
    name: $[[ inputs.src-folder ]] frontend
    deployment_tier: staging
    action: start

$[[ inputs.src-folder ]] preprod deploy:
  extends: .staging deploy template
  variables:
    TARGET_NETWORK: preprod
  needs: ["$[[ inputs.src-folder ]] preprod build"]
  script:
     - ENV=preprod dfx deploy --network $TARGET_NETWORK --no-wallet --mode reinstall -y $[[ inputs.src-folder ]]
  environment:
    name: $[[ inputs.src-folder ]] frontend
    deployment_tier: testing
    action: start



# PRODUCTION DEPLOYMENT

$[[ inputs.src-folder ]] production deploy:
  stage: deploy
  resource_group: frontend production deployment
  variables:
    PEM_FILE: "${PEM_FILE_PRODUCTION}"
    IS_SNS_CONTROLLED: $[[ inputs.sns-controlled ]]
    TARGET_NETWORK: ic
  needs: ["$[[ inputs.src-folder ]] production build"]
  rules:
    - if: $CI_COMMIT_TAG =~ '/^$[[ inputs.src-folder ]]-v\d+\.\d+\.\d+$/'
      changes:
        - "client/$[[ inputs.src-folder ]]/*.{js,json}"
        - "client/$[[ inputs.src-folder ]]/**/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
      when: manual
  before_script:
    - !reference [.import dfx identity, before_script]
  script:
     - ENV=prod dfx deploy --network $TARGET_NETWORK --no-wallet --mode reinstall -y $[[ inputs.src-folder ]]
  environment:
    name: $[[ inputs.src-folder ]] frontend
    deployment_tier: production
    action: start
