integration tests trigger:
  stage: integration_testing
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_REF_NAME != "develop"
      changes:
        - 'backend/libraries/**/*.{rs,toml,lock,md}'
        - 'backend/external_canisters/**/*.{rs,toml,lock,md}'
        - 'backend/canisters/**/*.{rs,toml,lock,md}'
      when: manual
  script:
    - echo "Running integration tests"

integration tests:
  stage: integration_testing
  rules:
    - if: $CI_COMMIT_TAG =~ '/^[a-zA-Z0-9_]+-v\d+\.\d+\.\d+$/'
      when: always
    - if: $CI_COMMIT_REF_NAME == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - 'backend/libraries/**/*.{rs,toml,lock,md}'
        - 'backend/external_canisters/**/*.{rs,toml,lock,md}'
        - 'backend/canisters/**/*.{rs,toml,lock,md}'
  needs: [
      # 'gldt_swap integration-test build',
      'icp_neuron integration-test build',
      'management integration-test build',
      'sns_neuron_controller integration-test build',
      'sns_rewards integration-test build',
      'super_stats_v3 integration-test build',
      'token_metrics integration-test build',
      'gldt_swap integration-test build'
    ]
  extends: .rust template
  tags:
    - dind
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_SECURITY_OPT: '--security-opt seccomp=unconfined'
  script:
    - wget -O pocket-ic.gz https://github.com/dfinity/pocketic/releases/download/4.0.0/pocket-ic-x86_64-linux.gz
    - gzip -d pocket-ic.gz
    - chmod +x ./pocket-ic
    - mv ./pocket-ic ./backend/integration_testing/pocket-ic
    - ulimit -n 202400
    - ulimit -f 2024000
    - cargo test -p integration_testing
