# NodeJS & NextJS job template

.node template:
  image: node:18
  cache:
  - key: "node-$CI_COMMIT_REF_SLUG"
    paths:
      - .npm/
      - node_modules/
      - client/**/.next/
      - client/**/.npm/
      - client/**/node_modules/
  before_script:
    - release=$(curl --silent "https://api.github.com/repos/dfinity/candid/releases/latest" | grep -e '"tag_name"' | cut -c 16-25)
    - curl -fsSL https://github.com/dfinity/candid/releases/download/${release}/didc-linux64 > /usr/bin/didc
    - npm ci --cache .npm --prefer-offline
