# Rust / Cargo (for wasm builds) template

.rust template:
  tags:
    # - docker
    # - big
  image: registry.bochslerfinance.com/runners-images/dfinity-canisters/rust-dfinity-build-ci:latest@sha256:7a8c861d0bf4d3d31a4a423ee328f7b62b0a4faaa77ecf87d372a09178d1b33f
  before_script:
    - cargo --version
    - rustc --version
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - runner_unsupported
      - unknown_failure
