# Rust / Cargo (for wasm builds) template

.rust template:
  tags:
    - docker
    - big
  image: rust:slim-bookworm
  cache:
  - key: "rust-$CI_COMMIT_REF_SLUG"
    paths:
      - .cargo
      - backend/canisters/gldt_core/target
      - backend/canisters/icp_neuron/target
  before_script:
    - apt update > /dev/null && apt install -y wget build-essential pkg-config libssl-dev > /dev/null
    - rustup component add clippy
    - rustup target add wasm32-unknown-unknown
    - mkdir -pv .cargo
    - cargo install -q --root .cargo ic-wasm@0.5.0 candid-extractor cargo-tarpaulin
    - export PATH="$PWD/.cargo/bin:$PATH"
