# Rust / Cargo (for wasm builds) template

.rust template:
  tags:
    - docker
    - big
  image: rust:slim-bookworm
  cache:
  - key: "rust-$CI_COMMIT_REF_SLUG"
    paths:
      - .cargo
      - backend/canisters/gldt_core/target
      - backend/canisters/icp_neuron/target
      - backend/canisters/token_metrics/target
      - backend/canisters/sns_rewards/target
  before_script:
    - apt update -y > /dev/null && apt install -y wget pkg-config libssl-dev > /dev/null
    - apt-get install build-essential -y
    - apt-get install autoconf libtool -y
    - apt-get install libssl-dev -y
    - apt-get install gcc-multilib -y
    - apt-get install gcc cmake -y
    - rustup toolchain install stable
    - rustup component add clippy
    - rustup target add wasm32-unknown-unknown
    - rustup target add x86_64-unknown-linux-gnu
    - mkdir -pv .cargo
    - wget -O pocket-ic.gz https://github.com/dfinity/pocketic/releases/download/3.0.1/pocket-ic-x86_64-linux.gz
    - gzip -d pocket-ic.gz
    - mv ./pocket-ic ./backend/integration_testing/pocket-ic
    - chmod +x ./backend/integration_testing/pocket-ic
    - cargo install -q --root .cargo ic-wasm@0.5.0 candid-extractor cargo-tarpaulin
    - ulimit -n 102400
    - ulimit -f 1024000 
    - export PATH=$PATH:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
    - export PATH="$PWD/.cargo/bin:$PATH"
