[package]
name = "integration-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-cdk = {workspace = true}
pocket-ic = {workspace = true}
candid = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
types = { path = '../libraries/types' }
utils = { path = '../libraries/utils' }