[package]
name = "ogy_sns_rewards_api_canister"
version = "0.1.0"
description = "Rewards canister to distribute custom token rewards for SNS participants."
edition = "2021"

[dependencies]
candid = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sns_governance_canister = { path = '../../../external_canisters/sns_governance/api' }
types = { path = '../../../libraries/types' }
