[package]
name = "gldt_swap_api_canister"
version = "0.1.0"
description = "GLDT forward and reserve swap to GLD - api"
edition = "2021"

[features]
default = []  # Empty default features
inttest = []

[dependencies]
candid = { workspace = true }
icrc-ledger-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
types = { path = '../../../libraries/types' }
gldt_swap_common = { path = "../common", features = []}
utils = { path = '../../../libraries/utils' }
bity-ic-icrc3 = { version =  "0.5.0" } # , features = ["debug-logs"]
bity-ic-types = { workspace = true }
gldt_swap_api_archive = { path = "../../../external_canisters/gldt_swap_archive/api" }