[package]
name = "gldt_swap_api_canister"
version = "0.1.0"
description = "GLDT forward and reserve swap to GLD - api"
edition = "2021"

[features]
default = []  # Empty default features
inttest = []

[dependencies]
candid = { workspace = true }
icrc-ledger-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
origyn_nft_reference = { path = '../../../external_canisters/origyn_nft_reference/api' }
types = { path = '../../../libraries/types' }
gldt_swap_common = { path = "../common", features = []}
utils = { path = '../../../libraries/utils' }
bity-ic-types = { workspace = true }