[package]
name = "gldt_stake"
version = "0.1.0"
description = "GLDT stake backend application - impl"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[features]
default = []  # Empty default features
inttest = ["gldt_stake_common/inttest", "gldt_stake_api_canister/inttest", ]

[dependencies]
candid = { workspace = true }
bity-ic-canister-logger = { workspace = true }
bity-ic-canister-state-macros = { workspace = true }
bity-ic-canister-time = { workspace = true }
bity-ic-canister-tracing-macros = { workspace = true }
http_request = { path = '../../../libraries/http_request' }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-stable-structures = { workspace = true }
icrc-ledger-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
icrc_ledger_canister_c2c_client = { path = "../../../external_canisters/icrc_ledger/c2c_client" }
serde_json = { workspace =  true }
icrc_ledger_canister = { path = "../../../external_canisters/icrc_ledger/api" }
bity-ic-stable-memory = { workspace = true }
types = { path = '../../../libraries/types' }
utils = { path = '../../../libraries/utils' }
tracing = { workspace = true }
gldt_stake_api_canister = { path = "../api"}
gldt_stake_common = { path = "../common"}
sns_governance_canister = { path = "../../../external_canisters/sns_governance/api" }
sns_governance_canister_c2c_client = { path = "../../../external_canisters/sns_governance/c2c_client" }
bity-ic-ledger-utils = { workspace = true }
time = { workspace = true }
sns_rewards_api_canister = {path = "../../sns_rewards/api"}
sns_rewards_c2c_client = {path = "../../../external_canisters/sns_rewards/c2c_client"}
icpswap_token_canister_c2c_client = { path = "../../../external_canisters/icpswap_token_canister/c2c_client" }
bity-ic-icrc3 = { workspace = true }
bity-ic-icrc3-macros = { workspace = true }
lazy_static = { workspace = true }
sha2 = { workspace = true }
bity-ic-serializer = { workspace = true }
futures = { workspace = true }
ic-cdk-timers = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
bity-ic-types = { workspace = true }