[package]
name = "usdg_minter"
version = "0.1.0"
description = "USDG protocol"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[features]
default = []  # Empty default features
inttest = []

[dependencies]
candid = { workspace = true }
gldt_swap_common = { path = "../../gldt_swap/common" }
ic0 = { workspace = true }
ic-canisters-http-types = { git = "https://github.com/dfinity/ic.git", rev = "1488a310043f6a0907f4a84ba7af00e3d90d16eb" }
ic-canister-log = "0.2.0"
ic-cdk = { workspace = true }
ic-xrc-types = { workspace = true }
icrc-ledger-types = { git = "https://github.com/dfinity/ic.git", rev = "1488a310043f6a0907f4a84ba7af00e3d90d16eb" }
icrc-ledger-client-cdk = { git = "https://github.com/dfinity/ic.git", rev = "1488a310043f6a0907f4a84ba7af00e3d90d16eb" }
ic-metrics-encoder = { workspace = true }
minicbor = { workspace = true }
minicbor-derive = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
usdg_minter_api = { path = "../api" }

[dev-dependencies]
proptest = "1.5.0"
assert_matches = { workspace = true }