[package]
name = "gldt_swap_archive"
version = "0.1.0"
description = "GLDT forward and reserve swap to GLD NFT - archive"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[features]
default = []  # Empty default features
inttest = ["gldt_swap_common/inttest",  "gldt_swap_api_archive/inttest"]

[dependencies]
candid = { workspace = true }
bity-ic-canister-logger = { workspace = true }
bity-ic-canister-state-macros = { workspace = true }
bity-ic-canister-tracing-macros = { workspace = true }
http_request = { path = '../../../libraries/http_request' }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-stable-structures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
bity-ic-serializer = { workspace = true }
bity-ic-stable-memory = { workspace = true }
types = { path = '../../../libraries/types' }
utils = { path = '../../../libraries/utils' }
tracing = { workspace = true }
gldt_swap_api_archive = { path = "../api_archive", features = []}
gldt_swap_common = { path = "../common", features = []}
