[package]
name = "gldt_stake_api_canister"
version = "0.1.0"
description = "GLDT stake backend application - api"
edition = "2021"

[features]
default = []  # Empty default features
inttest = []

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
icrc-ledger-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sns_governance_canister = { path = '../../../external_canisters/sns_governance/api' }
types = { path = '../../../libraries/types' }
gldt_stake_common = { path = "../common", features = []}
bity-ic-icrc3 = { workspace = true }
utils = { path = '../../../libraries/utils' }