[package]
name = "gldt_swap_api_archive"
version = "0.1.0"
description = "GLDT forward and reserve swap to GLD - api"
edition = "2021"

[features]
default = []  # Empty default features
inttest = []

[dependencies]
candid = { workspace = true }
serde = { workspace = true, features = ["derive"] }
types = { path = '../../../libraries/types' }
gldt_swap_common = { path = "../common", features = []}
