[package]
name = "icpswap_swap_pool_canister_c2c_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
canister_client = { path = "../../../libraries/canister_client" }
icpswap_swap_pool_canister = { path = "../api" }
types = { path = "../../../libraries/types" }
ic-cdk = { workspace = true }
candid = { workspace = true }