[package]
name = "gldt_stake_archive_c2c_client"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
canister_client = { path = "../../../libraries/canister_client" }
gldt_stake_api_archive = { path = "../../../canisters/gldt_stake/api_archive" }
gldt_stake_common = { path = "../../../canisters/gldt_stake/common" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
